-- 開発環境だけの仮の航海データと接続時間規則（Bolt 17 の確認ポイント 6・7）。dev のときだけ Flyway の場所に足す。
-- 航海番号と港の組合せは架空（実在の船会社・船名を使わない）。
-- 日時は起動した日の 0 時（UTC）を基準にした相対にする（Bolt 18。デモ環境は起動のたびに初期状態に戻るため、いつ起動しても
-- 期限が先にあり候補が出る）。CURRENT_DATE は日の中で変わらないため、サンプルの業務データ（V20261007120900）の希望到着期限
-- （基準の 26 日後、日本時間 9 時）と同じ基準になる。東京（JPTYO）→ ロッテルダム（NLRTM）で、その期限について、
-- 適合・期限と同時刻・接続不足・期限超過・規則のない港が見える組合せにする。
-- 外部原本の取込（US-14、W7）と、業務責任者の必要最小接続時間（DM-05、W6）が届いたら差し替える。

INSERT INTO routing.voyage (voyage_number, adopted_info_version, source_kind, source_ref, acquired_at, version, updated_at) VALUES
    ('DEMO-101', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR),
    ('DEMO-201', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR),
    ('DEMO-202', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR),
    ('DEMO-301', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR),
    ('DEMO-302', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR),
    ('DEMO-303', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR),
    ('DEMO-304', 'PROVISIONAL-1', 'MANUAL_ENTRY', '仮の航海データ（Bolt 17）', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR, 0, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) - INTERVAL '1' DAY + INTERVAL '6' HOUR);

-- DEMO-101: 直行（適合）。DEMO-201: 東京 → シンガポール。DEMO-202: 東京 → 香港（香港には規則がない）
-- DEMO-301: シンガポールで接続 12 時間、到着が期限と同時刻（適合）。DEMO-302: 接続 4 時間（接続不足）。
-- DEMO-303: 到着が期限の 1 日 12 時間後（期限超過）。DEMO-304: 香港 → ロッテルダム（接続を判定できない）
INSERT INTO routing.port_call (voyage_number, call_no, port_unlocode, arrival_at, departure_at) VALUES
    ('DEMO-101', 1, 'JPTYO', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '5' DAY),
    ('DEMO-101', 2, 'NLRTM', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '23' DAY + INTERVAL '9' HOUR, NULL),
    ('DEMO-201', 1, 'JPTYO', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '3' DAY),
    ('DEMO-201', 2, 'SGSIN', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '13' DAY, NULL),
    ('DEMO-202', 1, 'JPTYO', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '4' DAY),
    ('DEMO-202', 2, 'HKHKG', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '8' DAY, NULL),
    ('DEMO-301', 1, 'SGSIN', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '13' DAY + INTERVAL '12' HOUR),
    ('DEMO-301', 2, 'NLRTM', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '26' DAY, NULL),
    ('DEMO-302', 1, 'SGSIN', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '13' DAY + INTERVAL '4' HOUR),
    ('DEMO-302', 2, 'NLRTM', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '24' DAY, NULL),
    ('DEMO-303', 1, 'SGSIN', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '14' DAY),
    ('DEMO-303', 2, 'NLRTM', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '27' DAY + INTERVAL '12' HOUR, NULL),
    ('DEMO-304', 1, 'HKHKG', NULL, CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '9' DAY),
    ('DEMO-304', 2, 'NLRTM', CAST(CURRENT_DATE AS TIMESTAMP WITH TIME ZONE) + INTERVAL '22' DAY, NULL);

-- シンガポールの必要最小接続時間（仮に 8 時間。S-06 の画面イメージの値。DM-05 で差し替える）
INSERT INTO routing.connection_rule (id, route_scope, port_unlocode, min_connection_minutes, valid_from, valid_to, version)
VALUES ('00000000-0000-0000-0000-000000001701', '*', 'SGSIN', 480, TIMESTAMP WITH TIME ZONE '2026-01-01 00:00:00+00', NULL, 0);
